### ISSUE TITLE
Searching in static blocks generate an error

### ISSUE THREAD

**Issue by tig-dennisvanderhammen** [strakertranslations/magento-extension#1]
Hi,

One of our clients is using your extension. They contacted us about their static block page generates an error. We found out that the cause is the strakertranslations extension. We were also able to reproduce it on a core Magento environment.

If you go to CMS -> Static Blocks and insert a search value in one of the fields the following error is generated: https://screencast.com/t/J4iSHbLM

Installed Magento version: 1.8.1.0
Installed extension version: 1.3.9

**Comment by paul-at-straker** [comment]
Thanks for reporting this issue, the issue will be fixed in next release. 

Cheers.

**Comment by tig-dennisvanderhammen** [comment]
Hi Paul,
I see that you committed a new version of this extension. Does this new version also solve this issue? I would like to hear from you.

**Comment by paul-at-straker** [comment]
HI @tig-dennisvanderhammen, 
Yes, the version of 1.4.0 has fixed that issue. Thank you.

**Comment by tig-dennisvanderhammen** [comment]
Thank you for your quick response and your time.
